### ISSUE TITLE
Try to test against Chromium or Firefox

### ISSUE THREAD

**Issue by bxs9775** [Fractionators/sugarizer#9]
Ideally this project should work on a free browser, and multiple browsers. The first one should be tested by using a free browser, the second one should be tested using a browser that isn't Chrome.

**Comment by megancs601** [comment]
You can download Chromium x64 for windows from here https://chromium.woolyss.com/
I tested it out and Sugarizer works just fine on Chromium.

**Comment by ghost** [comment]
On Wed, Apr 19, 2017 at 06:35:49AM -0700, Megan Smith wrote:
> You can download Chromium x64 from here https://chromium.woolyss.com/
> I tested it out and Sugarizer works just fine on Chromium.

Not that Reddit is the last word on this,

https://www.reddit.com/r/Chromium/comments/4xjn52/can_i_trust_chromium_of_chromiumwoolysscom/

but I'm not sure why you wouldn't get Chromium from

https://download-chromium.appspot.com/

-- 
Joe

**Comment by megancs601** [comment]
I did try https://download-chromium.appspot.com/ but when I tried to run it, nothing happened. The browser opened but nothing loaded (grey screen in the Chromium browser). I figured it was because the download was for Windows x86 and I was trying to run that on a Windows x64.
I tried looking for a Chromium that ran on Windows  x64 on the same website but found nothing.
